# Gradle performance
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true
org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_id=portal_frame_whitelist
mod_version=1.0.0+26.2
maven_group=com.wh0oo
archives_base_name=portal_frame_whitelist

# Dependencies
fabric_version=0.152.0+26.2
